trigger:
  branches:
    include:
      - main
      - dev
      - test

variables:
  imageName: 'java-app'
  acrLoginServer: 'devacr.azurecr.io'
  imageTag: $(Build.BuildId)

stages:

# ==========================
# BUILD STAGE
# ==========================
- stage: Build
  displayName: 'Build & Push Image'

  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest

    steps:

    - task: Maven@3
      displayName: 'Maven Build'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'

    - task: Docker@2
      displayName: 'Build and Push'
      inputs:
        command: buildAndPush
        containerRegistry: 'Acr-Service-Connection'
        repository: $(imageName)
        dockerfile: 'Dockerfile'
        tags: |
          $(imageTag)

# ==========================
# DEV DEPLOYMENT
# ==========================
- stage: Dev
  displayName: 'Deploy to DEV'
  dependsOn: Build

  jobs:
  - deployment: DeployDev
    environment: DEV

    strategy:
      runOnce:
        deploy:
          steps:

          - task: KubernetesManifest@1
            displayName: Deploy to DEV AKS
            inputs:
              action: deploy
              kubernetesServiceConnection: 'AKS-DEV-CONNECTION'
              namespace: dev
              manifests: |
                manifests/dev/deployment.yaml
                manifests/dev/service.yaml

# ==========================
# QA DEPLOYMENT
# ==========================
- stage: QA
  displayName: 'Deploy to QA'
  dependsOn: Dev

  jobs:
  - deployment: DeployQA
    environment: QA

    strategy:
      runOnce:
        deploy:
          steps:

          - task: KubernetesManifest@1
            displayName: Deploy to QA AKS
            inputs:
              action: deploy
              kubernetesServiceConnection: 'AKS-QA-CONNECTION'
              namespace: qa
              manifests: |
                manifests/qa/deployment.yaml
                manifests/qa/service.yaml

# ==========================
# PROD DEPLOYMENT
# ==========================
- stage: Prod
  displayName: 'Deploy to PROD'
  dependsOn: QA

  jobs:
  - deployment: DeployProd
    environment: PROD

    strategy:
      runOnce:
        deploy:
          steps:

          - task: KubernetesManifest@1
            displayName: Deploy to PROD AKS
            inputs:
              action: deploy
              kubernetesServiceConnection: 'AKS-PROD-CONNECTION'
              namespace: prod
              manifests: |
                manifests/prod/deployment.yaml
                manifests/prod/service.yaml