trigger:
  branches:
    include:
      - main

variables:
  imageName: 'java-app'
  dockerFilePath: 'Dockerfile'
  acrName: 'devacr'
  acrLoginServer: 'devacr.azurecr.in'
  aksResourceGroup: 'devrsg'
  aksClusterName: 'devaks'
  namespace: 'dev'
  tags: $(Build.BuildId)

stages:
- stage: Build
  displayName: "Build with Maven"
  jobs:
  - job: BuildPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      displayName: "Build with Maven"
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'

    - task: Docker@2
      displayName: "Build and Push Docker Image"
      inputs:
        command: buildAndPush
        containerRegistry: 'Acr-service-connection'
        repository: $(imageName)
        dockerfile: $(dockerFilePath)
        tags: |
          $(tags)

- stage: Deploy
  displayName: "Deploy to AKS"
  dependsOn: Build
  jobs:
  - job: DeployToAKS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: "Deploy through CLI"
      inputs:
        azureSubscription: 'aks-service-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName)
           kubectl apply -f deployment.yaml -n $(namespace)